import { Project } from '../types/Project';

export const PROJECTS: Project[] = [
  {
    title: 'shopping mall',
    period: '2026.03 - 2026.03',
    description: '복잡한 이커머스 시스템을 현대적 아키텍처로 재해석한 풀스택 프로젝트입니다.',
    stack: ['Next.js', 'Spring Boot', 'TypeScript', 'PostgreSQL(Supabase)', 'Docker'],
    problem: '대규모 트래픽 보안 및 의존성 이슈.',
    solution: 'Spring Security/JWT 무상태 인증 및 AWS SDK 지연 초기화 전략.',
    links: { demo: 'https://shoppingmallfrontend.vercel.app/' },
  },
  {
    title: 'Milk Tycoon',
    period: '2026.03 - 2026.03',
    description: '추억의 게임을 현대적으로 재해석한 인터랙티브 게임입니다.',
    stack: ['React', 'TypeScript', 'Vite', 'Tailwind CSS'],
    problem: '게임 로딩 속도 저하 및 복잡한 UI.',
    solution: '코드 스플리팅 및 이미지 최적화로 로딩 속도 40% 단축.',
    links: { github: 'https://hamjoong.github.io/portfolio/milktycoon/' },
  },
  {
    title: 'Kiosk',
    period: '2022.09 - 2022.10',
    description: '주문 및 결제 과정을 간소화하는 사용자 친화적 솔루션입니다.',
    stack: ['Pug', 'Scss', 'JavaScript', 'jQuery', 'JSON'],
    problem: '페이지 로딩 및 이미지 최적화 미흡.',
    solution: '비동기 데이터 로딩 및 이미지 최적화로 로딩 속도 50% 개선.',
    links: { github: 'https://github.com/hamjoong/portfolio/tree/main/kiosk' },
  },
  {
    title: 'Note Pad',
    period: '2022.08 - 2022.09',
    description: '효율적인 아이디어 기록을 지원하는 애플리케이션입니다.',
    stack: ['Pug', 'Scss', 'JavaScript', 'jQuery', 'Node.js', 'MySQL'],
    problem: '성능 저하 및 데이터 충돌 문제.',
    solution: '실시간 동기화 및 버전 관리 도입.',
    links: { github: 'https://github.com/hamjoong/portfolio/tree/main/notepad' },
  },
  {
    title: 'Matrix Calculator',
    period: '2022.08 - 2022.08',
    description: '행렬 연산 결과를 시각적으로 제공하는 계산 도구입니다.',
    stack: ['Pug', 'Scss', 'JavaScript', 'jQuery'],
    problem: '대규모 연산 시 렌더링 성능 저하.',
    solution: '가상 DOM을 활용한 렌더링 최적화(70% 개선).',
    links: { github: 'https://github.com/hamjoong/portfolio/tree/main/matrixcalculator' },
  },
  {
    title: 'Movie Box',
    period: '2022.08 - 2022.08',
    description: '영화 탐색 플랫폼입니다.',
    stack: ['Pug', 'Scss', 'JavaScript', 'jQuery'],
    problem: '로딩 속도 및 복잡한 인터페이스.',
    solution: '직관적인 인터페이스 재설계.',
    links: { github: 'https://github.com/hamjoong/portfolio/tree/main/movie' },
  },
  {
    title: 'Ssn Validation',
    period: '2022.08 - 2022.08',
    description: '주민등록번호 유효성 검증 애플리케이션입니다.',
    stack: ['Html', 'Scss', 'JavaScript'],
    problem: '복잡한 유효성 검증 로직.',
    solution: '검증 로직 간소화 및 UI 개선.',
    links: { github: 'https://github.com/hamjoong/portfolio/tree/main/ssnvalidation' },
  },
];
