export const tagSynonyms: { [key: string]: string } = {
  // IT - Frontend
  '프론트엔드': 'FRONTEND',
  'FRONTEND': 'FRONTEND',
  'FRONT END': 'FRONTEND',
  'frontend': 'FRONTEND',
  'front end': 'FRONTEND',
  '프론트': 'FRONTEND',
  'FE': 'FRONTEND',
  'fe': 'FRONTEND',
  '리액트': 'REACT',
  'REACT': 'REACT',
  'React': 'REACT',
  'react': 'REACT',
  '리액트JS': 'REACT',
  'REACTJS': 'REACT',
  'REACT JS': 'REACT',
  'reactjs': 'REACT',
  'react js': 'REACT',
  '자바스크립트': 'JAVASCRIPT',
  'JAVASCRIPT': 'JAVASCRIPT',
  'JAVA SCRIPT': 'JAVASCRIPT',
  'javascript': 'JAVASCRIPT',
  'java script': 'JAVASCRIPT',
  'JavaScript': 'JAVASCRIPT',
  'JS': 'JAVASCRIPT',
  '자스': 'JAVASCRIPT',

  // IT - Backend
  '백엔드': 'BACKEND',
  'BACKEND': 'BACKEND',
  'BACK END': 'BACKEND',
  'backend': 'BACKEND',
  'back end': 'BACKEND',
  'BE': 'BACKEND',
  'be': 'BACKEND',
  '자바': 'JAVA',
  'JAVA': 'JAVA',
  'java': 'JAVA',
  '스프링부트': 'SPRINGBOOT',
  'SPRINGBOOT': 'SPRINGBOOT',
  'SPRING BOOT': 'SPRINGBOOT',
  'springboot': 'SPRINGBOOT',
  'spring boot': 'SPRINGBOOT',
  '스프링': 'SPRINGBOOT',
  '스프링 부트': 'SPRINGBOOT',
  '노드제이에스': 'NODEJS',
  'NODEJS': 'NODEJS',
  'NODE JS': 'NODEJS',
  'nodejs': 'NODEJS',
  'node js': 'NODEJS',
  '노드': 'NODEJS',

  // IT - Fullstack & Others
  '풀스택': 'FULLSTACK',
  'FULLSTACK': 'FULLSTACK',
  'FULL STACK': 'FULLSTACK',
  'FULL-STACK': 'FULLSTACK',
  'fullstack': 'FULLSTACK',
  'full stack': 'FULLSTACK',
  'full-stack': 'FULLSTACK',
  'FS': 'FULLSTACK',
  'fs': 'FULLSTACK',
  '데이터베이스': 'DB',
  'DATABASE': 'DB',
  'DATA BASE': 'DB',
  'database': 'DB',
  'data base': 'DB',
  'DB': 'DB',
  'db': 'DB',
  '디비': 'DB',
  '타입스크립트': 'TYPESCRIPT',
  'TYPESCRIPT': 'TYPESCRIPT',
  'TYPE SCRIPT': 'TYPESCRIPT',
  'typescript': 'TYPESCRIPT',
  'type script': 'TYPESCRIPT',
  'TypeScript': 'TYPESCRIPT',
  'TS': 'TYPESCRIPT',
  'ts': 'TYPESCRIPT',
  '타스': 'TYPESCRIPT',
  '타입스': 'TYPESCRIPT',
  '제이슨': 'JSON',
  'JSON': 'JSON',
  'json': 'JSON',
  
  // IT - DevOps
  '데브옵스': 'DEVOPS',
  'DEVOPS': 'DEVOPS',
  'DEV OPS': 'DEVOPS',
  'devops': 'DEVOPS',
  'dev ops': 'DEVOPS',
  'DO': 'DEVOPS',
  'do': 'DEVOPS',

  // AI
  '챗지피티': 'CHATGPT',
  'CHATGPT': 'CHATGPT',
  'CHAT GPT': 'CHATGPT',
  'GPT': 'CHATGPT',
  'chatgpt': 'CHATGPT',
  'chat gpt': 'CHATGPT',
  'Chat GPT': 'CHATGPT',
  'chat GPT ': 'CHATGPT',
  '지피티': 'CHATGPT',
  '제미나이': 'GEMINI',
  'GEMINI': 'GEMINI',
  'gemini': 'GEMINI',
  'Gemini': 'GEMINI',
  '제미니': 'GEMINI',
  '클로드': 'CLAUDE',
  'CLAUDE': 'CLAUDE',
  'claude': 'CLAUDE',
  'Claude': 'CLAUDE',
  '엔트로픽': 'CLAUDE',
  'ANTHROPIC': 'CLAUDE',
  'anthropic': 'CLAUDE',
  'Anthropic': 'CLAUDE',
  'VS CODE': 'VSCODE',
  'VSCODE': 'VSCODE',
  'vs code': 'VSCODE',
  'vscode': 'VSCODE',
  'VSC': 'VSCODE',
  'vsc': 'VSCODE',
  'VSCode': 'VSCODE',
  '브이에스코드': 'VSCODE',
  'AI': 'AI',
  'ai': 'AI',
  '에이아이': 'AI',
  '인공지능': 'AI',
  '에이아이에이전트': 'AIAGENT',
  'AIAGENT': 'AIAGENT',
  'AI AGENT': 'AIAGENT',
  'aigent': 'AIAGENT',
  'ai agent': 'AIAGENT',
  'AI Agent': 'AIAGENT',
  '에이전트': 'AIAGENT',
  'AG': 'AIAGENT',
  'LLM': 'LLM',
  'llm': 'LLM',
  '대형언어모델': 'LLM',
  'LARGE LANGUAGE MODEL': 'LLM',
  'large language model': 'LLM',
  'Large Language Model': 'LLM',
  '라지 랭귀지 모델': 'LLM',
  '라지언어모델': 'LLM',
  '라지 랭귀지모델': 'LLM',
  '챗봇': 'CHATBOT',
  'CHATBOT': 'CHATBOT',
  'chatbot': 'CHATBOT',
  'Chatbot': 'CHATBOT',
  'Antigravity': 'ANTIGRAVITY',
  'ANTIGRAVITY': 'ANTIGRAVITY',
  'antigravity': 'ANTIGRAVITY',
  '안티그래비티': 'ANTIGRAVITY',
  '안티 그래비티': 'ANTIGRAVITY',
  'ag': 'ANTIGRAVITY',
  '안티그라비티': 'ANTIGRAVITY',
  '안티 그라비티': 'ANTIGRAVITY',
  '그래비티': 'ANTIGRAVITY',
  '그라비티': 'ANTIGRAVITY',
  'Cursor': 'CURSOR',
  'CURSOR': 'CURSOR',
  'cursor': 'CURSOR',
  '커서': 'CURSOR'
};

export const normalizeTag = (input: string): string => {
  const upper = input.trim().toUpperCase();
  // exact match in synonyms
  if (tagSynonyms[upper]) return tagSynonyms[upper];
  
  // partial match/clean up if not in synonyms
  return upper.replace(/\s+/g, '');
};
