-- devcodehub 운영 DB 스키마 (Supabase SQL Editor에서 한 번 실행)
-- 생성 방법: 로컬 Postgres 16에 local 프로필로 서버를 띄워 JPA가 만든 스키마를 pg_dump -s 로 추출 (2026-10-08)
-- 운영 프로필은 ddl-auto: none 이라 이 파일을 먼저 적용해야 서버가 동작한다.
-- 이 파일 하나로 backend/db/2026-10-08-*.sql 의 변경(payment_id 유니크, social_access_token 제거)도 이미 반영돼 있다.

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

--
-- Name: admin_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_logs (
    id bigint NOT NULL,
    action_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    reason text,
    admin_id bigint,
    target_user_id bigint,
    CONSTRAINT admin_logs_action_type_check CHECK (((action_type)::text = ANY ((ARRAY['CREDIT_ADJUST'::character varying, 'BOARD_DELETE'::character varying, 'COMMENT_DELETE'::character varying, 'REVIEW_CANCEL'::character varying])::text[])))
);

--
-- Name: admin_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: badges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.badges (
    id bigint NOT NULL,
    condition_type character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    threshold integer NOT NULL,
    CONSTRAINT badges_condition_type_check CHECK (((condition_type)::text = ANY ((ARRAY['XP'::character varying, 'POST_COUNT'::character varying, 'COMMENT_COUNT'::character varying, 'REVIEW_COUNT'::character varying])::text[])))
);

--
-- Name: badges_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.badges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.badges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: board_bookmarks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_bookmarks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    board_id bigint,
    user_id bigint
);

--
-- Name: board_bookmarks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.board_bookmarks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_bookmarks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: board_likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_likes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    board_id bigint,
    user_id bigint
);

--
-- Name: board_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.board_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: board_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_tags (
    board_id bigint NOT NULL,
    tag character varying(255)
);

--
-- Name: boards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.boards (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    view_count integer DEFAULT 0,
    user_id bigint NOT NULL,
    CONSTRAINT boards_type_check CHECK (((type)::text = ANY ((ARRAY['SKILL'::character varying, 'AI'::character varying])::text[])))
);

--
-- Name: boards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.boards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.boards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message text NOT NULL,
    type character varying(255) NOT NULL,
    chat_room_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT chat_messages_type_check CHECK (((type)::text = 'TALK'::text))
);

--
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: chat_room_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_room_users (
    id bigint NOT NULL,
    last_read_at timestamp(6) without time zone,
    last_read_message_id bigint,
    chat_room_id bigint NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: chat_room_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_room_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_room_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: chat_rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_rooms (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT chat_rooms_type_check CHECK (((type)::text = ANY ((ARRAY['SINGLE'::character varying, 'GROUP'::character varying])::text[])))
);

--
-- Name: chat_rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    board_id bigint NOT NULL
);

--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: credit_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_transactions (
    id bigint NOT NULL,
    amount integer NOT NULL,
    balance_after integer NOT NULL,
    created_at timestamp(6) without time zone,
    payment_id character varying(100),
    target_id bigint,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT credit_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['RECHARGE'::character varying, 'SUBSCRIBE'::character varying, 'REFUND'::character varying, 'SPEND_AI'::character varying, 'SPEND_SENIOR'::character varying, 'EARN_REVIEW'::character varying, 'COMMISSION'::character varying, 'ADMIN_ADJUST'::character varying])::text[])))
);

--
-- Name: credit_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: guest_usage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guest_usage (
    id bigint NOT NULL,
    ip_address character varying(255) NOT NULL,
    last_used_at timestamp(6) without time zone,
    usage_count integer NOT NULL
);

--
-- Name: guest_usage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guest_usage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guest_usage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    is_read boolean NOT NULL,
    user_id bigint
);

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    ai_result text,
    code_content text NOT NULL,
    created_at timestamp(6) without time zone,
    language character varying(255) NOT NULL,
    model_name character varying(255) NOT NULL,
    structured_result jsonb,
    title character varying(255) NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: senior_review_applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.senior_review_applications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message text NOT NULL,
    request_id bigint NOT NULL,
    senior_id bigint NOT NULL
);

--
-- Name: senior_review_applications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.senior_review_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.senior_review_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: senior_review_request_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.senior_review_request_tags (
    request_id bigint NOT NULL,
    tag character varying(255)
);

--
-- Name: senior_review_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.senior_review_requests (
    id bigint NOT NULL,
    code_content text NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    credits integer NOT NULL,
    language character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    junior_id bigint NOT NULL,
    senior_id bigint,
    CONSTRAINT senior_review_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'MATCHED'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])))
);

--
-- Name: senior_review_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.senior_review_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.senior_review_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: senior_reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.senior_reviews (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    rating integer NOT NULL,
    request_id bigint NOT NULL,
    senior_id bigint NOT NULL
);

--
-- Name: senior_reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.senior_reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.senior_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: senior_verifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.senior_verifications (
    id bigint NOT NULL,
    blog_url character varying(255),
    career_summary text NOT NULL,
    created_at timestamp(6) without time zone,
    github_url character varying(255),
    linkedin_url character varying(255),
    rejection_reason character varying(255),
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT senior_verifications_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

--
-- Name: senior_verifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.senior_verifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.senior_verifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: user_badges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_badges (
    user_id bigint NOT NULL,
    badge_id bigint NOT NULL
);

--
-- Name: user_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_subscriptions (
    id bigint NOT NULL,
    active boolean NOT NULL,
    expired_at timestamp(6) without time zone NOT NULL,
    paid_amount integer NOT NULL,
    plan character varying(255) NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_subscriptions_plan_check CHECK (((plan)::text = ANY ((ARRAY['WEEKLY'::character varying, 'MONTHLY'::character varying, 'YEARLY'::character varying])::text[])))
);

--
-- Name: user_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    address character varying(500),
    avatar_url character varying(255),
    contact character varying(255),
    created_at timestamp(6) without time zone,
    credits integer NOT NULL,
    email character varying(255) NOT NULL,
    experience integer NOT NULL,
    level integer NOT NULL,
    login_id character varying(255) NOT NULL,
    max_weekly_free_limit integer NOT NULL,
    nickname character varying(255) NOT NULL,
    password character varying(255),
    profile_image_url character varying(255),
    provider character varying(255),
    provider_id character varying(255),
    role character varying(255) NOT NULL,
    total_spent_credits integer NOT NULL,
    weekly_free_review_used integer NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'SENIOR'::character varying, 'ADMIN'::character varying, 'GUEST'::character varying])::text[])))
);

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: admin_logs admin_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_logs
    ADD CONSTRAINT admin_logs_pkey PRIMARY KEY (id);

--
-- Name: badges badges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badges
    ADD CONSTRAINT badges_pkey PRIMARY KEY (id);

--
-- Name: board_bookmarks board_bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_bookmarks
    ADD CONSTRAINT board_bookmarks_pkey PRIMARY KEY (id);

--
-- Name: board_likes board_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_likes
    ADD CONSTRAINT board_likes_pkey PRIMARY KEY (id);

--
-- Name: boards boards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT boards_pkey PRIMARY KEY (id);

--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);

--
-- Name: chat_room_users chat_room_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_room_users
    ADD CONSTRAINT chat_room_users_pkey PRIMARY KEY (id);

--
-- Name: chat_rooms chat_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT chat_rooms_pkey PRIMARY KEY (id);

--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

--
-- Name: credit_transactions credit_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_transactions
    ADD CONSTRAINT credit_transactions_pkey PRIMARY KEY (id);

--
-- Name: guest_usage guest_usage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guest_usage
    ADD CONSTRAINT guest_usage_pkey PRIMARY KEY (id);

--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);

--
-- Name: senior_review_applications senior_review_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_review_applications
    ADD CONSTRAINT senior_review_applications_pkey PRIMARY KEY (id);

--
-- Name: senior_review_requests senior_review_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_review_requests
    ADD CONSTRAINT senior_review_requests_pkey PRIMARY KEY (id);

--
-- Name: senior_reviews senior_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_reviews
    ADD CONSTRAINT senior_reviews_pkey PRIMARY KEY (id);

--
-- Name: senior_verifications senior_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_verifications
    ADD CONSTRAINT senior_verifications_pkey PRIMARY KEY (id);

--
-- Name: guest_usage uk11d6pgfs30ihyqh39ibmx4sga; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guest_usage
    ADD CONSTRAINT uk11d6pgfs30ihyqh39ibmx4sga UNIQUE (ip_address);

--
-- Name: senior_reviews uk42c31weswdmglwx0a8ik4etob; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_reviews
    ADD CONSTRAINT uk42c31weswdmglwx0a8ik4etob UNIQUE (request_id);

--
-- Name: board_likes uk9aqa1yn5n4xcg2t5exv1lwgfd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_likes
    ADD CONSTRAINT uk9aqa1yn5n4xcg2t5exv1lwgfd UNIQUE (board_id, user_id);

--
-- Name: user_subscriptions uka8455mp06snh8ry1uiy7s32d6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT uka8455mp06snh8ry1uiy7s32d6 UNIQUE (user_id);

--
-- Name: credit_transactions uka9u21gdgunu0t8kqvaa7ysoyi; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_transactions
    ADD CONSTRAINT uka9u21gdgunu0t8kqvaa7ysoyi UNIQUE (payment_id);

--
-- Name: badges ukcuebofvgkgi4g9fxde2kmpr1h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badges
    ADD CONSTRAINT ukcuebofvgkgi4g9fxde2kmpr1h UNIQUE (name);

--
-- Name: users uki3xs7wmfu2i3jt079uuetycit; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uki3xs7wmfu2i3jt079uuetycit UNIQUE (login_id);

--
-- Name: board_bookmarks ukpljm4xqa8wam9rdbctcnhagh1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_bookmarks
    ADD CONSTRAINT ukpljm4xqa8wam9rdbctcnhagh1 UNIQUE (board_id, user_id);

--
-- Name: user_subscriptions user_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: idx_board_content; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_board_content ON public.boards USING btree (content);

--
-- Name: idx_board_title; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_board_title ON public.boards USING btree (title);

--
-- Name: idx_board_type_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_board_type_created_at ON public.boards USING btree (type, created_at);

--
-- Name: idx_boards_fts; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_boards_fts ON public.boards USING btree (title, content);

--
-- Name: idx_chat_room_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_room_created_at ON public.chat_messages USING btree (chat_room_id, created_at);

--
-- Name: idx_chat_room_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_room_id ON public.chat_messages USING btree (chat_room_id, id);

--
-- Name: idx_transaction_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaction_user_created ON public.credit_transactions USING btree (user_id, created_at);

--
-- Name: idx_user_chat_room; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_chat_room ON public.chat_room_users USING btree (user_id, chat_room_id);

--
-- Name: idx_user_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_email ON public.users USING btree (email);

--
-- Name: idx_user_nickname; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_nickname ON public.users USING btree (nickname);

--
-- Name: senior_verifications fk2klsimfjvog7ifrwmboo5r33p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_verifications
    ADD CONSTRAINT fk2klsimfjvog7ifrwmboo5r33p FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: board_tags fk34wt4k44nof2kiwqdun2yes6a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_tags
    ADD CONSTRAINT fk34wt4k44nof2kiwqdun2yes6a FOREIGN KEY (board_id) REFERENCES public.boards(id);

--
-- Name: user_subscriptions fk3l40lbyji8kj5xoc20ycwsc8g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT fk3l40lbyji8kj5xoc20ycwsc8g FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: senior_review_applications fk5t5728x3rvrckrwed2nuj72he; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_review_applications
    ADD CONSTRAINT fk5t5728x3rvrckrwed2nuj72he FOREIGN KEY (senior_id) REFERENCES public.users(id);

--
-- Name: chat_messages fk6f0y4l43ihmgfswkgy9yrtjkh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk6f0y4l43ihmgfswkgy9yrtjkh FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: board_bookmarks fk7ej5nmcdpxocis2itwykht4mk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_bookmarks
    ADD CONSTRAINT fk7ej5nmcdpxocis2itwykht4mk FOREIGN KEY (board_id) REFERENCES public.boards(id);

--
-- Name: boards fk7kt8hby5livgmjj15f79e9t6v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT fk7kt8hby5livgmjj15f79e9t6v FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: comments fk8omq0tc18jd43bu5tjh6jvraq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: senior_review_requests fk9wyqg3r969dvpkk1lrubep4x0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_review_requests
    ADD CONSTRAINT fk9wyqg3r969dvpkk1lrubep4x0 FOREIGN KEY (senior_id) REFERENCES public.users(id);

--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: chat_room_users fka4i754uhscevbsye3dmeuma5t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_room_users
    ADD CONSTRAINT fka4i754uhscevbsye3dmeuma5t FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: chat_messages fkbcsxusjp1v4rd8879fhvq8ssb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkbcsxusjp1v4rd8879fhvq8ssb FOREIGN KEY (chat_room_id) REFERENCES public.chat_rooms(id);

--
-- Name: reviews fkcgy7qjc1r99dp117y9en6lxye; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: board_bookmarks fkcwufx74qordx1v0aj259d17ab; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_bookmarks
    ADD CONSTRAINT fkcwufx74qordx1v0aj259d17ab FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: senior_review_request_tags fkd6o21yb8sbcc2e6r00k8w4521; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_review_request_tags
    ADD CONSTRAINT fkd6o21yb8sbcc2e6r00k8w4521 FOREIGN KEY (request_id) REFERENCES public.senior_review_requests(id);

--
-- Name: senior_review_requests fkea4l344ab9rt29u1hnlvaihs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_review_requests
    ADD CONSTRAINT fkea4l344ab9rt29u1hnlvaihs FOREIGN KEY (junior_id) REFERENCES public.users(id);

--
-- Name: senior_review_applications fkhvig66iqey7mofonlqigv1oe4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_review_applications
    ADD CONSTRAINT fkhvig66iqey7mofonlqigv1oe4 FOREIGN KEY (request_id) REFERENCES public.senior_review_requests(id);

--
-- Name: credit_transactions fkjl0dwyeb8wag4j40g87uhvk8d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_transactions
    ADD CONSTRAINT fkjl0dwyeb8wag4j40g87uhvk8d FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: user_badges fkk6e00pguaij0uke6xr81gt045; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT fkk6e00pguaij0uke6xr81gt045 FOREIGN KEY (badge_id) REFERENCES public.badges(id);

--
-- Name: chat_room_users fkmnm9x3nr1fe9ukjgi5ykofvsx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_room_users
    ADD CONSTRAINT fkmnm9x3nr1fe9ukjgi5ykofvsx FOREIGN KEY (chat_room_id) REFERENCES public.chat_rooms(id);

--
-- Name: board_likes fkn6r8psm1l68teg04e86e19lev; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_likes
    ADD CONSTRAINT fkn6r8psm1l68teg04e86e19lev FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: comments fko7l08y12wlmjbt81ey5wysk2g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fko7l08y12wlmjbt81ey5wysk2g FOREIGN KEY (board_id) REFERENCES public.boards(id);

--
-- Name: admin_logs fkoix4xxbvhimiroqel44k3h7uk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_logs
    ADD CONSTRAINT fkoix4xxbvhimiroqel44k3h7uk FOREIGN KEY (admin_id) REFERENCES public.users(id);

--
-- Name: senior_reviews fkpfltl1yx569vvs3fnu6dhgd28; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_reviews
    ADD CONSTRAINT fkpfltl1yx569vvs3fnu6dhgd28 FOREIGN KEY (senior_id) REFERENCES public.users(id);

--
-- Name: senior_reviews fkpoinc6mni71c3sguf9nkumid1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.senior_reviews
    ADD CONSTRAINT fkpoinc6mni71c3sguf9nkumid1 FOREIGN KEY (request_id) REFERENCES public.senior_review_requests(id);

--
-- Name: board_likes fkq0j8j4h4bhcsgsndjaoqr0cmy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_likes
    ADD CONSTRAINT fkq0j8j4h4bhcsgsndjaoqr0cmy FOREIGN KEY (board_id) REFERENCES public.boards(id);

--
-- Name: admin_logs fkqxmccwsgq2jtihfnijo9t3qjc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_logs
    ADD CONSTRAINT fkqxmccwsgq2jtihfnijo9t3qjc FOREIGN KEY (target_user_id) REFERENCES public.users(id);

--
-- Name: user_badges fkr46ah81sjymsn035m4ojstn5s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT fkr46ah81sjymsn035m4ojstn5s FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- PostgreSQL database dump complete
--

-- [Why] Supabase는 public 스키마 테이블을 공개 키(anon)로 직접 읽을 수 있게 열어 둔다.
-- 이 앱은 백엔드(서버 계정)만 DB에 접속하므로 RLS를 켜고 정책을 만들지 않아 공개 키 접근을 모두 막는다.
ALTER TABLE public.admin_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_room_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.senior_review_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.senior_review_request_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.senior_review_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.senior_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.senior_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
