-- Core schema required by the catalog, cart, order, review, and Q&A Edge Functions.
-- New projects start with an empty catalog; product/category seed data is separate.
BEGIN;

-- Empty compatibility table required by the historical account-mapping
-- migration in the repository's ordered migration chain. New accounts belong
-- only in auth.users; do not seed legacy users into this table.
CREATE TABLE IF NOT EXISTS public.users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email varchar(100) NOT NULL UNIQUE,
    role varchar(20) NOT NULL DEFAULT 'ROLE_USER',
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    parent_id bigint REFERENCES public.categories (id) ON DELETE SET NULL,
    display_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.products (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id bigint REFERENCES public.categories (id) ON DELETE SET NULL,
    name varchar(200) NOT NULL,
    description text,
    price numeric(12, 2) NOT NULL CHECK (price >= 0),
    stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    main_image_url varchar(1000),
    sales_count integer NOT NULL DEFAULT 0 CHECK (sales_count >= 0),
    view_count integer NOT NULL DEFAULT 0 CHECK (view_count >= 0),
    version bigint NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'FOR_SALE'
        CHECK (status IN ('FOR_SALE', 'SOLD_OUT', 'HIDDEN')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.product_options (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE CASCADE,
    option_type varchar(100) NOT NULL,
    option_name varchar(100) NOT NULL,
    CONSTRAINT product_options_product_type_name_unique UNIQUE (product_id, option_type, option_name),
    additional_price numeric(12, 2) NOT NULL DEFAULT 0,
    stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cart_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id text NOT NULL,
    product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE CASCADE,
    option_id text,
    quantity integer NOT NULL CHECK (quantity > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.orders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_no varchar(50) NOT NULL UNIQUE,
    user_id text NOT NULL,
    total_amount numeric(12, 2) NOT NULL CHECK (total_amount >= 0),
    status varchar(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'PAID', 'SHIPPED', 'COMPLETED', 'CANCELLED')),
    receiver_name varchar(120) NOT NULL,
    phone varchar(20) NOT NULL,
    postal_code varchar(20),
    address varchar(300) NOT NULL,
    detail_address varchar(300) NOT NULL DEFAULT '',
    memo text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL REFERENCES public.orders (id) ON DELETE CASCADE,
    product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE RESTRICT,
    option_id text,
    quantity integer NOT NULL CHECK (quantity > 0),
    price numeric(12, 2) NOT NULL CHECK (price >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.reviews (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id text NOT NULL,
    product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE CASCADE,
    order_id uuid REFERENCES public.orders (id) ON DELETE SET NULL,
    rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
    content text NOT NULL,
    image_url varchar(1000),
    admin_reply text,
    replied_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.product_qnas (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id text NOT NULL,
    product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE CASCADE,
    title varchar(500) NOT NULL,
    content text NOT NULL,
    answer text,
    is_answered boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_product_category_status
    ON public.products (category_id, status);
CREATE INDEX IF NOT EXISTS idx_product_price
    ON public.products (price);
CREATE INDEX IF NOT EXISTS idx_product_created
    ON public.products (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_sales
    ON public.products (sales_count DESC);
CREATE INDEX IF NOT EXISTS idx_product_option_product
    ON public.product_options (product_id);
CREATE UNIQUE INDEX IF NOT EXISTS cart_items_owner_product_option_idx
    ON public.cart_items (user_id, product_id, option_id) NULLS NOT DISTINCT;
CREATE INDEX IF NOT EXISTS idx_order_user_created
    ON public.orders (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order
    ON public.order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product_created
    ON public.reviews (product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_user_created
    ON public.reviews (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_qnas_product_created
    ON public.product_qnas (product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_qnas_user_created
    ON public.product_qnas (user_id, created_at DESC);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_qnas ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE
    public.users,
    public.categories,
    public.products,
    public.product_options,
    public.cart_items,
    public.orders,
    public.order_items,
    public.reviews,
    public.product_qnas
FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE
    public.users,
    public.categories,
    public.products,
    public.product_options,
    public.cart_items,
    public.orders,
    public.order_items,
    public.reviews,
    public.product_qnas
TO service_role;
DO $$
DECLARE
    category_sequence text := pg_get_serial_sequence('public.categories', 'id');
BEGIN
    IF category_sequence IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO service_role', category_sequence);
    END IF;
END;
$$;

COMMIT;
