     name: Shoppingmall Deploy
    
     on:
       push:
         branches:
           - main
       workflow_dispatch:
    
     jobs:
      deploy-test:
        runs-on: ubuntu-latest
        steps:
          - name: Say Hello
            run: echo "Hello World"